"""add_pokemon_habitat

Revision ID: 1a18e259c72c
Revises: 8c5a5382b805
Create Date: 2026-03-24 23:28:37.275960

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a18e259c72c"
down_revision: str | Sequence[str] | None = "8c5a5382b805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pokemon", sa.Column("habitat", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pokemon", "habitat")
    # ### end Alembic commands ###
